version: '3'
services:
  frontend:
    build: ../fronted 
    ports:
      - "5002:5002"  # Фронтенд должен использовать порт 5002
    environment:
      - FLASK_APP=add
    command: ["flask", "run", "--host=0.0.0.0", "--port=5002"] 
    networks:
      - mynet
    depends_on:
      - backend  

  backend:
    build: ../backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=back
    command: ["flask", "run", "--host=0.0.0.0", "--port=5001"]
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
