version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network

  front:
    build: ../fronted
    ports:
      - "5002:5002"
    networks:
      - my-network

  back:
    build: ../backend
    ports:
      - "5001:5001"
    networks:
      - my-network

networks:
  my-network:
    driver: "bridge"
