version: '3.8'

services:
  frontend:
    build: ../fronted
    dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=add
    command: ["python", "add.py"]

  backend:
    build: ../backend
    dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=back
    command: ["python", "back.py"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount Nginx configuration
    depends_on:
      - fronted
      - backend
