services:
  front:
    build: ../fronted
    ports:
      - "5002:5000"
    environment:
      - FLASK_APP=add
    command: ["flask", "run", "--host=0.0.0.0"]

  back:
    build: ../backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=back
    command: ["flask", "run", "--host=0.0.0.0"]
