version: '3'

services:
  back:
    build: ../backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=back
    command: ["flask", "run", "--host=0.0.0.0", "--port=5001"]

  front:
    build: ../frontend
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=add
    command: ["flask", "run", "--host=0.0.0.0", "--port=5002"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /opt/projects/DevOps/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - back
      - front
