version: '3'
services:
  front:
    build: ../fronted
    ports:
      - "5002:5001"
    environment:
      - FLASK_APP=add
    command: ["flask", "run", "--host=0.0.0.0", "--port=5001"]
    networks:
      - mynet
    depends_on:
      - back

  back:
    build: ../backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=back
    command: ["flask", "run", "--host=0.0.0.0", "--port=5001"]
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
