services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - devops-network

  backend:
    build: ./backend
    restart: always
    networks:
      - devops-network
    volumes:
      - ./data.txt:/app/data.txt

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge
