version: '3'

services:
  front:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=add
    command: ["flask", "run", "--host=0.0.0.0"]

  back:
    build: ./back
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=back
    command: ["flask", "run", "--host=0.0.0.0"]
