version: '3'

services:
  back:
    build: ../backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=back
    command: ["flask", "run", "--host=0.0.0.0", "--port=5001"]

  front:
    build: ../frontend
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=add
    command: ["flask", "run", "--host=0.0.0.0", "--port=5002"]

  nginx:
    build: .
    ports:
      - "80:80"
    depends_on:
      - back
      - front
