services:
  frontend:
    build: ./fronted
    ports:
      - "5002:5002"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5001:5001"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
